#!/bin/bash

wget https://www.cl.cam.ac.uk/teaching/2021/Databases/movies-relational.zip
unzip movies-relational.zip

if [ ! -f neo4j-community-4.1.3-unix.tar.gz ]; then
  wget http://dist.neo4j.org/neo4j-community-4.1.3-unix.tar.gz
fi

tar -xvf neo4j-community-4.1.3-unix.tar.gz
mv neo4j-community-4.1.3 ${CONDA_DIR}/
rm neo4j-community-4.1.3-unix.tar.gz

# Not sure if the neo4j web UI is working via the proxy
# This should allow the db to listen if it does...
# Comment it out if you'd rather be a bit more secure
echo "dbms.connectors.default_listen_address=0.0.0.0" >> ${CONDA_DIR}/neo4j-community-4.1.3/conf/neo4j.conf

# neo4j has aa default password: neo4j
# However, if you log in with that, the session will soon time out
# and you will be required to update the original default password 
${CONDA_DIR}/neo4j-community-4.1.3/bin/neo4j-admin set-initial-password neo4jbinder

# database
cd /tmp

git clone https://github.com/eohomegrownapps/build_databases.cst.cam.ac.uk
cd build_databases.cst.cam.ac.uk
# python build_IMDb_raw.py
# python build_IMDb_relational.py
# python build_IMDb_graph.py

sed -i 's+\$NEO4JBINPATH+${CONDA_DIR}/neo4j-community-4.1.3/bin+g' neo4j_load.sh

./neo4j_load.sh